# Generated by Django 5.0.4 on 2024-04-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_remove_expense_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='main_app.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
