# Generated by Django 5.0.4 on 2024-04-16 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_subcategory_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.subcategory'),
            preserve_default=False,
        ),
    ]
