# Generated by Django 5.0.4 on 2024-04-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_expense_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget_date',
            field=models.DateField(blank=True),
        ),
    ]
