# Generated by Django 5.0.4 on 2024-04-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_expense_budget_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget_date',
            field=models.DateField(null=True),
        ),
    ]
