# Generated by Django 5.0.4 on 2024-04-16 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_expense_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.subcategory'),
        ),
    ]
